version: "3.9"
services:
  caixara-db:
    image: postgres:latest
    container_name: caixara-db
    networks:
      - orchestrator-saga
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: caixara-db
    ports:
      - "5436:5432"
networks:
  orchestrator-saga:
    driver: bridge
